version: "3.9"
services:
  apache:
    image: php-redis-alex:latest
    restart: unless-stopped
    volumes: 
      - ./key/:/etc/apache2/external/
      - /home/alex/ftp/files/AdminBSBMaterialDesign-master/:/var/www/html
      - ./dataNILMTK/nilmtk2/models/:/models/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
  nilmtk:
    image: "nilmtk"
    container_name: nilmtk
    restart: unless-stopped
    volumes:
      - ./dataNILMTK/:/root/data/
    network_mode: host
    command: cron -f
networks:
    backend:
      name: backend

